extensions:
  health_check:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
    
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 30
  batch:
  
exporters:
  debug:
  otlp/jaeger:
    endpoint: "${JAEGER_ENDPOINT}"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors: [memory_limiter, batch]
      exporters:
        - debug
        - otlp/jaeger
  extensions:
    - health_check
    - zpages 