// <auto-generated />
using System;
using InvoiceAPI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceAPI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InvoiceDbContext))]
    [Migration("20250527174134_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("InvoiceDbContext")
                .HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("InvoiceAPI.Domain.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("IssuingDate")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InvoiceDbContext_Invoices", "InvoiceDbContext");
                });

            modelBuilder.Entity("Microservice.Common.Domain.Events.Producer.IntegrationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BodyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("TraceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InvoiceDbContext_Outbox", "InvoiceDbContext");
                });

            modelBuilder.Entity("InvoiceAPI.Domain.Models.Invoice", b =>
                {
                    b.OwnsMany("InvoiceAPI.Domain.Models.Service", "_services", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("AssetId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Price")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly?>("ValidFrom")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("InvoiceId");

                            b1.ToTable("InvoiceDbContext_Services", "InvoiceDbContext");

                            b1.WithOwner("Invoice")
                                .HasForeignKey("InvoiceId");

                            b1.Navigation("Invoice");
                        });

                    b.Navigation("_services");
                });
#pragma warning restore 612, 618
        }
    }
}
